#!/bin/bash

function parse_http_response_code() {
  set +x
  printf "$1"| awk '/HTTP/' | awk '{print $2}'
}

function parse_value_from_response() {
  set +x

  json=$(printf "$1" | awk -v pattern="$2" '$0~pattern' | awk '{print $0}')
  jq -n "${json}" | jq --arg pattern "$2" '.[$pattern]'
}

