#!/bin/bash

function get_virtual_host_by_host_port() {

  set +x

  password="${1}"
  endpoint="${2}"
  host_port="${3}"

  get_virtual_hosts_response=$(curl -k \
    -s \
    -i \
    -u "Administrator:${password}" \
    -H 'X-Xsrf-Header: PingAccess' \
    "${endpoint}/virtualhosts?virtualHost=${host_port}")

  get_virtual_hosts_response_code=$(parse_http_response_code "${get_virtual_hosts_response}")

  if [[ 200 -ne ${get_virtual_hosts_response_code} ]]; then
    echo "There was a problem getting the virtual host: " ${get_virtual_hosts_response_code}
    return 1
  else
    echo "${get_virtual_hosts_response}"
    return 0
  fi
}

function get_agent_by_name() {

  set +x

  password="${1}"
  endpoint="${2}"
  name="${3}"

  get_agent_response=$(curl -k \
    -s \
    -i \
    -u "Administrator:${password}" \
    -H 'X-Xsrf-Header: PingAccess' \
    "${endpoint}/agents?name=${name}")

  get_agent_response_code=$(parse_http_response_code "${get_agent_response}")

  if [[ 200 -ne ${get_agent_response_code} ]]; then
    echo "There was a problem getting the agent: " ${get_agent_response_code}
    return 1
  else
    echo "${get_agent_response}"
    return 0
  fi
}

function get_application_by_name() {

  set +x

  password="${1}"
  endpoint="${2}"
  name="${3}"

  get_app_response=$(curl -k \
    -s \
    -i \
    -u "Administrator:${password}" \
    -H 'X-Xsrf-Header: PingAccess' \
    "${endpoint}/applications?name=${name}")

  get_app_response_code=$(parse_http_response_code "${get_app_response}")

  if [[ 200 -ne ${get_app_response_code} ]]; then
    echo "There was a problem getting the application: " ${get_app_response_code}
    return 1
  else
    echo "${get_app_response}"
    return 0
  fi
}