# Customer-hub overrides for p1as-observability.
#
# ### prometheus-agent ###
# 1. opensearch-grafana-credentials: The secret is created by p14c-integration in os-controller-manager which only 
#    runs in the non-chub-envs. Remove volume mounts for prometheus-agent can start without the secret in customer-hub envs.
#
# ### nri-bundle.newrelic-prometheus-agent ###
# 1. opensearch-newrelic-credentials: The secret is created by p14c-integration in os-controller-manager which only 
#    runs in non-chub envs. Remove volume mounts for the newrelic-prometheus-agent so it can start without the 
#    secret in customer-hub envs
prometheus-agent:
  server:
    # Override extraVolumes and extraVolumeMounts to empty arrays. Since customer-hub does not deploy OpenSearch,
    # the opensearch-grafana-credentials secret will not exist and clearing these mounts prevents pod startup failure.
    extraVolumes: []
    extraVolumeMounts: []

nri-bundle:
  newrelic-prometheus-agent:
    extraVolumes: []
    extraVolumeMounts: []


