apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Patch the CRDs such that argocd will sync them properly
patchesJson6902:
  - target:
      version: v1
      kind: CustomResourceDefinition
      name: grafanas.grafana.integreatly.org
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: grafanadashboards.grafana.integreatly.org
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"  

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: grafanadatasources.grafana.integreatly.org
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"  

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: grafanafolders.grafana.integreatly.org
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: opensearchactiongroups.opensearch.opster.io
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: opensearchclusters.opensearch.opster.io
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: opensearchcomponenttemplates.opensearch.opster.io
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: opensearchindextemplates.opensearch.opster.io
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: opensearchismpolicies.opensearch.opster.io
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: opensearchroles.opensearch.opster.io
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: opensearchtenants.opensearch.opster.io
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: opensearchuserrolebindings.opensearch.opster.io
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: opensearchusers.opensearch.opster.io
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"
