{
 "title": "PingOne Advanced Services Ingress Usage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ingressName",
    "query": {
     "query": "label_values(kube_ingress_labels,ingress)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"$ingressName\"}[5m]) * 60) by (status)",
     "legendFormat": "Status: {{status}}"
    }
   ]
  },
  {
   "title": "Bytes transferred / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_bytes_sent_sum{ingress=\"$ingressName\"}[5m]) * 60) by (path, status)",
     "legendFormat": "Path: {{path}} - Status: {{status}}"
    },
    { "expr": "ingress" }
   ]
  },
  {
   "title": "Backend requests / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_count{ingress=\"$ingressName\"}[5m]) * 60) by (method, status)",
     "legendFormat": "{{method}} - Status: {{status}}"
    }
   ]
  },
  {
   "title": "Backend response time ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_response_duration_seconds_count{ingress=\"$ingressName\"}[5m])*1000) by (method, status)",
     "legendFormat": "{{method}} - Status: {{status}}"
    }
   ]
  }
 ]
}