{
 "title": "PingAccess Per-Server Dashboard",
 "description": "PingAccess Metrics by Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JVM GC CPU, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"pa-jmx-exporter\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{instance}} - {{gc}}"
    }
   ]
  },
  {
   "title": "JVM GC Old Gen (Tenured) Collected, %",
   "type": "timeseries",
   "description": "JVM GC Old Gen (Tenured) Collected, %\\n\\nFormula: GC Old Gen (Tenured) Collection Usage Used / GC Old Gen (Tenured) Collection Usage Max * 100 ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(java_lang_PS_Old_Gen_CollectionUsage_used{job=\"pa-jmx-exporter\", namespace=\"$namespace\"} or java_lang_Tenured_Gen_CollectionUsage_used{job=\"pa-jmx-exporter\", namespace=\"$namespace\"})/(java_lang_PS_Old_Gen_CollectionUsage_max{job=\"pa-jmx-exporter\", namespace=\"$namespace\"} or java_lang_Tenured_Gen_CollectionUsage_max{job=\"pa-jmx-exporter\", namespace=\"$namespace\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Time 90 Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingaccess_response_time_statistics_90_percentile{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Time Mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingaccess_response_time_statistics_mean{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Concurrency 90 Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingaccess_response_concurrency_statistics_90_percentile{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Concurrency Mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingaccess_response_concurrency_statistics_mean{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingaccess_response_statistics_count{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}