{
 "title": "PingDirectory Topology Dashboard",
 "description": "Overall Topology Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "LDAP Users Count",
   "type": "timeseries",
   "description": "Count of users",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "max(users_count_1)", "legendFormat": "Count of users 1" },
    { "expr": "max(users_count_2)", "legendFormat": "Count of users 2" },
    { "expr": "max(users_count_3)", "legendFormat": "Count of users 3" },
    { "expr": "max(users_count_4)", "legendFormat": "Count of users 4" }
   ]
  },
  {
   "title": "Throughput by Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation) (throughput{namespace=\"$namespace\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Overall Operation Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(throughput{namespace=\"$namespace\"})",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Average Latency by Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (operation) (response_time{namespace=\"$namespace\"} > 0)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Overall Average Operation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg((response_time{namespace=\"$namespace\"} > 0))"
    }
   ]
  },
  {
   "title": "Garbage Collection Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (gcType, size, cause) (rate(garbage_collections{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{gcType}}-{{size}}-{{cause}}"
    }
   ]
  },
  {
   "title": "Replication Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "replica_backlog {namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Entry Count by Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (backendID) (backend_entry_count{namespace=\"$namespace\"})",
     "legendFormat": "{{backendID}}"
    }
   ]
  },
  {
   "title": "Average GC Live Megabytes by Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (region) (garbage_collection_live_megabytes{namespace=\"$namespace\"})",
     "legendFormat": "{{region}}"
    }
   ]
  }
 ]
}