[OUTPUT]
    Name                http
    Alias               s3_app_out
    Match               *
    # Default is workers=1 for all outputs; increased for s3 to handle high-volume.
    workers             3
    Host                logstash-elastic-s3.elastic-stack-logging
    Port                8081
    Format              json
    Retry_Limit         False
    compress            gzip
    net.keepalive_idle_timeout  10
    net.keepalive_max_recycle   100
    storage.total_limit_size  4000M

[OUTPUT]
    Name                http
    Alias               logstash_elk_out
    Match               elk.kube.*
    workers             2
    Host                logstash-elastic.elastic-stack-logging
    Port                8080
    Format              json
    Retry_Limit         10
    compress            gzip
    net.keepalive_idle_timeout  10
    net.keepalive_max_recycle   100
    storage.total_limit_size  2000M

[OUTPUT]
    Name                http
    Alias               logstash_customer_out
    Match               elk.kube.*
    workers             2
    Host                logstash-elastic.elastic-stack-logging
    Port                8084
    Format              json
    Retry_Limit         10
    compress            gzip
    net.keepalive_idle_timeout  10
    net.keepalive_max_recycle   100
    storage.total_limit_size  2000M
