########################################################################################################################
# This file provides sample patches to update the following settings for each provisioned app:
#
#   - HPA min/max replicas and target CPU utilization
#   - Memory/CPU requests/limits
#   - Disk size
#
# It serves just as a sample and not included from any kustomization.yaml file. PS/GSO must update the
# custom-patches.yaml file using these snippets as appropriate for a customer environment for it to be effective.
########################################################################################################################


---

################################################
#                Logstash
################################################

### Update logstash replicas count

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: logstash-elastic
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: logstash-elastic

---

### Update logstash replicas count and adjust resources

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: logstash-elastic
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: logstash-elastic
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: "1.7"
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 3.7Gi
---

################################################
#                Karpenter
################################################
### The karpenter will stay disabled until all customers have been upgraded.
### Scale down cluster-autoscaler replicas to zero
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  replicas: 0

---

################################################
#                ArgoCD
################################################
# The custom logging verbosity level for the below pods is added. So we don’t need to implement it from scratch.

# argocd-dex-server
# argocd-repo-server (only git-ops-command container)

# Added a patch for the above pods in k8s-configs/cluster-tools/base/git-ops/argo/kustomization.yaml file. 
# If we want to change the logging level change the inline in command to one of  debug|info|warn|error
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      containers:
      - name: dex
        command:
        - sh
        - -c
        - /shared/argocd-dex rundex --loglevel error
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: git-ops-command
        command: 
        - sh
        - -c
        - /var/run/argocd/argocd-cmp-server --loglevel error

---
