apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-elastic
  namespace: elastic-stack-logging
spec:
  template:
    spec:
      initContainers:
      - name: opensearch-bootstrap
        $patch: delete
