kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- common
- enrichment
- logstash
- namespace.yaml

configMapGenerator:
- name: elk-environment-variables
  envs:
  - env_vars
