apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: logstash-elastic
spec:
  behavior:
    scaleDown:
      policies:
        - periodSeconds: 30
          type: Percent
          value: 25
      selectPolicy: Max
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 2
          periodSeconds: 120
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Pods
      pods:
        metric:
          name: logstash_queue_utilization_percent
        target:
          type: AverageValue
          averageValue: "20"
  # Rate of Events coming to Logstash  
    - type: Pods
      pods:
        metric:
          name: logstash_events_in_rate
        target:
          type: AverageValue
          averageValue: "1500m"
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: logstash-elastic

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: logstash-elastic-s3
spec:
  behavior:
    scaleDown:
      policies:
        - periodSeconds: 30
          type: Percent
          value: 25
      selectPolicy: Max
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 2
          periodSeconds: 120
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Pods
      pods:
        metric:
          name: logstash_queue_utilization_percent
        target:
          type: AverageValue
          averageValue: "20"
    - type: Pods
      pods:
        metric:
          name: logstash_events_in_rate
        target:
          type: AverageValue
          averageValue: "1500m"
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: logstash-elastic-s3
