apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: logstash-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: logstash-elastic

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: logstash-s3-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: logstash-elastic-s3
