name: Auto-label PRs

on:
  pull_request:
    types: [opened, reopened, ready_for_review, converted_to_draft]

jobs:
  label-prs:
    uses: ping-internal/p1as-eng-tools/.github/workflows/label-prs.yml@master
    permissions:
      pull-requests: write
      issues: write
